language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.6
 - 3.5
 - 3.4

sudo: false

install:
 - pip install pyflakes pycodestyle

script:
 # Pretend tests
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
